// Real investor data - Top 12 VCs in Nordics & Europe (expandable to 100+)
export const INVESTOR_SEED_DATA = [
  // NORDIC TIER 1
  {
    name: "Creandum",
    firmName: "Creandum",
    type: "vc",
    website: "https://www.creandum.com",
    linkedIn: "https://linkedin.com/company/creandum",
    stage: ["seed", "series_a", "series_b"],
    industries: ["saas", "fintech", "marketplace", "consumer"],
    geographies: ["nordics", "europe"],
    checkSizeMin: 500000,
    checkSizeMax: 15000000,
    thesis: "Early-stage technology companies with global ambitions",
    sweetSpot: "B2B SaaS and marketplaces with strong network effects",
    portfolioCount: 80,
    notableInvestments: ["Spotify", "Klarna", "iZettle", "Depop", "Bolt"],
    fundSize: 500000000,
    yearFounded: 2003,
    dealsPerYear: 8,
    tags: ["b2b", "saas", "fintech", "marketplace"],
    ranking: 100
  },
  {
    name: "Northzone",
    firmName: "Northzone",
    type: "vc",
    website: "https://www.northzone.com",
    linkedIn: "https://linkedin.com/company/northzone",
    stage: ["seed", "series_a", "series_b"],
    industries: ["saas", "fintech", "health tech", "sustainability"],
    geographies: ["nordics", "europe", "us"],
    checkSizeMin: 1000000,
    checkSizeMax: 20000000,
    thesis: "Technology-driven companies solving important problems",
    sweetSpot: "B2B SaaS with strong unit economics",
    portfolioCount: 150,
    notableInvestments: ["Spotify", "Klarna", "iZettle", "Trustpilot", "Hopin"],
    fundSize: 1000000000,
    yearFounded: 1996,
    dealsPerYear: 12,
    tags: ["b2b", "saas", "fintech", "health"],
    ranking: 98
  },
  {
    name: "Atomico",
    firmName: "Atomico",
    type: "vc",
    website: "https://www.atomico.com",
    linkedIn: "https://linkedin.com/company/atomico",
    stage: ["series_a", "series_b", "series_c"],
    industries: ["saas", "fintech", "deep_tech", "marketplace"],
    geographies: ["europe", "us"],
    checkSizeMin: 5000000,
    checkSizeMax: 100000000,
    thesis: "Disruptive technology companies led by exceptional founders",
    sweetSpot: "European tech scaling globally",
    portfolioCount: 100,
    notableInvestments: ["Klarna", "Supercell", "Lilium", "MessageBird", "Pipedrive"],
    fundSize: 1200000000,
    yearFounded: 2006,
    dealsPerYear: 10,
    tags: ["b2b", "saas", "fintech", "deep_tech"],
    ranking: 96
  },
  {
    name: "Accel",
    firmName: "Accel",
    type: "vc",
    website: "https://www.accel.com",
    linkedIn: "https://linkedin.com/company/accel-partners",
    stage: ["seed", "series_a", "series_b", "series_c"],
    industries: ["saas", "fintech", "consumer", "marketplace"],
    geographies: ["us", "europe", "india"],
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    thesis: "Bold entrepreneurs building world-changing companies",
    sweetSpot: "Category-defining companies with network effects",
    portfolioCount: 500,
    notableInvestments: ["Facebook", "Spotify", "Slack", "Dropbox", "Figma"],
    fundSize: 3000000000,
    yearFounded: 1983,
    dealsPerYear: 20,
    tags: ["b2b", "consumer", "saas", "marketplace"],
    ranking: 95
  },
  {
    name: "Index Ventures",
    firmName: "Index Ventures",
    type: "vc",
    website: "https://www.indexventures.com",
    linkedIn: "https://linkedin.com/company/index-ventures",
    stage: ["seed", "series_a", "series_b", "series_c"],
    industries: ["saas", "fintech", "gaming", "security"],
    geographies: ["europe", "us"],
    checkSizeMin: 1000000,
    checkSizeMax: 50000000,
    thesis: "Exceptional founders solving big problems with technology",
    sweetSpot: "SaaS and fintech with strong product-market fit",
    portfolioCount: 200,
    notableInvestments: ["Dropbox", "Slack", "Figma", "Discord", "Revolut"],
    fundSize: 2000000000,
    yearFounded: 1996,
    dealsPerYear: 15,
    tags: ["b2b", "saas", "fintech", "gaming"],
    ranking: 94
  },
  {
    name: "Antler",
    firmName: "Antler",
    type: "vc",
    website: "https://www.antler.co",
    linkedIn: "https://linkedin.com/company/antler",
    stage: ["pre_seed", "seed"],
    industries: ["saas", "fintech", "marketplace", "health tech"],
    geographies: ["global"],
    checkSizeMin: 100000,
    checkSizeMax: 500000,
    thesis: "Backing exceptional founders from day zero",
    sweetSpot: "Pre-seed and seed stage across all sectors",
    portfolioCount: 700,
    notableInvestments: ["Juni", "Cove", "Reals", "Cloosiv"],
    fundSize: 50000000,
    yearFounded: 2017,
    dealsPerYear: 100,
    tags: ["pre_seed", "global", "generalist"],
    ranking: 85
  },
  {
    name: "EQT Ventures",
    firmName: "EQT Ventures",
    type: "vc",
    website: "https://eqtgroup.com/ventures",
    linkedIn: "https://linkedin.com/company/eqt-ventures",
    stage: ["series_a", "series_b"],
    industries: ["saas", "fintech", "health tech", "sustainability"],
    geographies: ["europe", "us"],
    checkSizeMin: 5000000,
    checkSizeMax: 30000000,
    thesis: "Data-driven investing in category-leading companies",
    sweetSpot: "B2B software with AI/ML capabilities",
    portfolioCount: 60,
    notableInvestments: ["Wolt", "Epidemic Sound", "Small Giant Games"],
    fundSize: 1100000000,
    yearFounded: 2016,
    dealsPerYear: 8,
    tags: ["b2b", "ai", "data_driven"],
    ranking: 88
  },
  {
    name: "Inventure",
    firmName: "Inventure",
    type: "vc",
    website: "https://www.inventure.vc",
    linkedIn: "https://linkedin.com/company/inventure",
    stage: ["seed", "series_a"],
    industries: ["saas", "marketplace", "fintech"],
    geographies: ["nordics", "baltics"],
    checkSizeMin: 500000,
    checkSizeMax: 5000000,
    thesis: "Nordic entrepreneurs building global software companies",
    sweetSpot: "Early-stage SaaS with product-market fit",
    portfolioCount: 50,
    notableInvestments: ["Wolt", "Swappie", "Recordly"],
    fundSize: 150000000,
    yearFounded: 2005,
    dealsPerYear: 10,
    tags: ["nordics", "saas", "early_stage"],
    ranking: 82
  },
  {
    name: "Nordic Makers",
    firmName: "Nordic Makers",
    type: "vc",
    website: "https://www.nordicmakers.vc",
    linkedIn: "https://linkedin.com/company/nordic-makers",
    stage: ["pre_seed", "seed"],
    industries: ["saas", "deep_tech", "climate"],
    geographies: ["nordics"],
    checkSizeMin: 250000,
    checkSizeMax: 2000000,
    thesis: "Technical founders building in public",
    sweetSpot: "Developer tools and infrastructure",
    portfolioCount: 30,
    notableInvestments: ["Krea", "Lovable", "Runway"],
    fundSize: 30000000,
    yearFounded: 2020,
    dealsPerYear: 15,
    tags: ["technical_founders", "dev_tools", "open_source"],
    ranking: 78
  },
  {
    name: "Balderton Capital",
    firmName: "Balderton Capital",
    type: "vc",
    website: "https://www.balderton.com",
    linkedIn: "https://linkedin.com/company/balderton-capital",
    stage: ["series_a", "series_b", "series_c"],
    industries: ["saas", "fintech", "marketplace", "gaming"],
    geographies: ["europe"],
    checkSizeMin: 3000000,
    checkSizeMax: 50000000,
    thesis: "European founders building global category leaders",
    sweetSpot: "Series A SaaS companies",
    portfolioCount: 200,
    notableInvestments: ["Revolut", "GoCardless", "Depop", "Nutmeg"],
    fundSize: 1300000000,
    yearFounded: 2000,
    dealsPerYear: 12,
    tags: ["europe", "saas", "fintech"],
    ranking: 92
  },
  {
    name: "Lakestar",
    firmName: "Lakestar",
    type: "vc",
    website: "https://www.lakestar.com",
    linkedIn: "https://linkedin.com/company/lakestar",
    stage: ["series_a", "series_b", "series_c"],
    industries: ["saas", "fintech", "consumer", "health tech"],
    geographies: ["europe", "us"],
    checkSizeMin: 5000000,
    checkSizeMax: 100000000,
    thesis: "Visionary founders creating transformative companies",
    sweetSpot: "European tech with global ambitions",
    portfolioCount: 70,
    notableInvestments: ["Spotify", "Opendoor", "Oscar Health", "Revolut"],
    fundSize: 1700000000,
    yearFounded: 2012,
    dealsPerYear: 8,
    tags: ["europe", "growth", "transformative"],
    ranking: 90
  },
  {
    name: "Point Nine",
    firmName: "Point Nine",
    type: "vc",
    website: "https://www.pointnine.com",
    linkedIn: "https://linkedin.com/company/point-nine",
    stage: ["seed", "series_a"],
    industries: ["saas", "marketplace"],
    geographies: ["europe", "us"],
    checkSizeMin: 500000,
    checkSizeMax: 10000000,
    thesis: "B2B SaaS and marketplaces with strong fundamentals",
    sweetSpot: "Early-stage SaaS with ARR traction",
    portfolioCount: 150,
    notableInvestments: ["Zendesk", "Delivery Hero", "Loom", "Algolia"],
    fundSize: 200000000,
    yearFounded: 2011,
    dealsPerYear: 15,
    tags: ["saas", "b2b", "fundamentals"],
    ranking: 87
  }
];

export const getInvestorsByStage = (stage: string) => {
  return INVESTOR_SEED_DATA.filter(inv => inv.stage.includes(stage));
};

export const getInvestorsByIndustry = (industry: string) => {
  return INVESTOR_SEED_DATA.filter(inv => inv.industries.includes(industry));
};

export const getInvestorsByGeography = (geo: string) => {
  return INVESTOR_SEED_DATA.filter(inv => inv.geographies.includes(geo));
};